[package]
name = "auction"
version = "3.0.1"
description = "Clearing algorithm for volume maximising uniform-price auction"
repository = "https://github.com/research-ag/auction"
keywords = [ "exchange", "tokens", "order-matching" ]
license = "Apache-2.0"

[dependencies]
core = "2.0.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"

[toolchain]
moc = "1.0.0"

[requirements]
moc = "1.0.0"
